<?php

/**
 * @file
 * Contains Afrikaburn Emails module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_entity_insert().
 */
function afrikaburn_emails_entity_insert($entity){
  _afrikaburn_emails_notify($entity, 'create');
}

/**
 * Implements hook_entity_update().
 */
function afrikaburn_emails_entity_update($entity){
  _afrikaburn_emails_notify($entity, 'update');
}

/**
 * Implements hook_mail().
 */
function afrikaburn_emails_mail($key, &$message, $params) {
  if ($key === 'ab_notification') {
    $message['from'] = \Drupal::config('system.site')->get('mail');
    $message['subject'] = $params['subject'];
    $message['body'][] = Html::escape($params['message']);
  }
}

// --- Message utilities

/**
 * Sends emails to notify users of actions
 * @param  [object] $entity Entity object being operated on
 * @param  [string] $action Action being performed
 */
function _afrikaburn_emails_notify($entity, $action){

  $token_service = \Drupal::token();  
  $configs = _afrikaburn_emails_get_config($entity, $action);

  if ($configs) {
    foreach($configs as $config){

      $recipients = _afrikaburn_emails_addresses($entity, $config['recipients']);
      // dpm($recipients);
      if (count($recipients)) {

        $recipient_string = implode(', ', $recipients);
        $message = \Drupal::token()->replace(
          $config['template'], 
          [
            $config['key'][2] => $entity
          ]
        );
        $subject = \Drupal::token()->replace(
          $config['subject'], 
          [
            $config['key'][2] => $entity
          ]
        );

        $result = \Drupal::service('plugin.manager.mail')->mail(
          'afrikaburn_emails',
          'ab_notification',
          $recipient_string,
          \Drupal::currentUser()->getPreferredLangcode(),
          [
            'subject' => $subject,
            'message' => $message,
          ],
          NULL, 
          TRUE
        );

        $result['result']
          ? \Drupal::logger('mail-log')->notice('Mail sent to ' . $recipient_string . "\n" . $subject . "\n:" . $message)
          : \Drupal::logger('mail-log')->notice('Mail send FAILED to ' . $recipient_string . "\n" . $subject . "\n:" . $message);
      } else {
        \Drupal::logger('mail-log')->notice('No recipients to send "' . $config['subject'] . '" email to');        
      }
    }
  }
}

// --- Recipient utilities

/**
 * Retrieves all recipients for a notification
 * @param  [object] $entity       Entity object being operated on
 * @param  [string] $recipients   Comma delimited string of recipient types
 * @return [array]                Array of email addresses
 */
function _afrikaburn_emails_addresses($entity, $recipients){

  $addresses = [];

  foreach(explode(',', $recipients) as $recipient){
    $recipient = trim($recipient);
    if (in_array($recipient, ['author', 'group', 'invitees', 'new_invitees'])) {
      $function = '_afrikaburn_emails_recipient_' . $recipient;
      $addresses += $function($entity);
    } else {
      $addresses[$recipient] = $recipient;
    }
  }

  return $addresses;
}

/**
 * Retrieves an author email address
 * @param  [object] $entity   Entity object being operated on
 * @return [array]            Array of email addresses
 */
function _afrikaburn_emails_recipient_author($entity){
  switch($entity->getEntityType()->id()){
    case 'user': $mail = $entity->getEmail(); return [$mail => $mail];
    case 'node': $mail = $entity->getOwner()->getEmail(); return [$mail => $mail];
    default: return [];
  }
}

/**
 * Retrieves a list of group member email addresses
 * @param  [object] $entity       Entity object being operated on
 * @return [array]            Array of email addresses
 */
function _afrikaburn_emails_recipient_group($entity){

  $members = [];
  $addresses = [];

  $field_collective = $entity->get('field_collective');
  if ($field_collective) {
    $collective = $field_collective->first();

    if ($collective) {
      $members = $collective
        ->get('entity');
        ->getTarget()
        ->get('field_col_members')
        ->referencedEntities();    
      foreach ($members as $member) {
        $email = $member->getEmail();
        $addresses[$email] = $email;
      }
    }
  }

  return $addresses;
}

/**
 * Retrieves a list of group member email addresses
 * @param  [object] $entity       Entity object being operated on
 * @return [array]            Array of email addresses
 */
function _afrikaburn_emails_recipient_invitees($entity){

  $invitees = [];

  $invitees = array_column(
    $entity
      ->get('field_col_invitee')
      ->getValue(),
    'value'
  );

  return array_combine($invitees, $invitees);
}

/**
 * Retrieves a list of group member email addresses
 * @param  [object] $entity       Entity object being operated on
 * @return [array]            Array of email addresses
 */
function _afrikaburn_emails_recipient_new_invitees($entity){

  $originals = $entity->original
      ->get('field_col_invitee')
      ->getValue()
      ? array_column(
          $entity->original
            ->get('field_col_invitee')
            ->getValue(),
          'value'
        )
      : [];

  $invitees = $entity
      ->get('field_col_invitee')
      ->getValue()
      ? array_column(
          $entity
            ->get('field_col_invitee')
            ->getValue(),
          'value'
        )
      : [];

  return array_diff($invitees, $originals);
}

// --- Config Utilities

/**
 * Retrieves the messaging configuration for an entity/action pair
 * @param  [object] $entity Entity object being operated on
 * @param  [string] $action Action being performed
 * @return [array|FALSE] configuration or FALSE if non-existent
 */
function _afrikaburn_emails_get_config($entity, $action){

  $config = \Drupal::config('afrikaburn_emails.settings');
  $message_definition = $config->get('message_definition');
  $target_key = _afrikaburn_emails_message_key($entity, $action);
  $matches = [];

  preg_match_all("/^[^\:]*\:" . $target_key . "(\:[^\|]*)?\|.*$/m", $message_definition, $matches);

  $configs = FALSE;
  foreach($matches[0] as $match){
    if (substr_count($match, '|') == 2) {
      list($key, $subject, $recipient) = explode('|', trim($match));
      $key_parts = explode(':', $key);
      $fields = TRUE;
      if (isset($key_parts[4])){
        foreach(explode('&', $key_parts[4]) as $field_name){
          $fields &= $field_name[0] == '!'
            ? !($entity->get(str_replace('!', '', $field_name))->getValue()[0]['value'])
            : $entity->get($field_name)->getValue()[0]['value'];
        }
      }
      if ($fields){
        $configs[] = [
          'key' => $key_parts,
          'subject' => $subject,
          'template' => $config->get($key_parts[0]),
          'recipients' => $recipient,
        ];
      }
    }
  }

  return $configs;
}

/**
 * Constructs a message key
 * @param  [object] $entity Entity object being operated on
 * @param  [string] $action Action being performed
 * @return [string]         Constructed configuration key
 */
function _afrikaburn_emails_message_key($entity, $action){

  $parts = [
    $action,
    $entity->getEntityTypeId(),
    $entity->bundle(),
  ];

  return implode(':', array_filter($parts));
}
