name: 'AfrikaBurn Configuration'
type: module
core: 8.x
dependencies:
  - basic_auth
  - block
  - block_content
  - block_place
  - ckeditor
  - comment
  - conditional_fields
  - contact
  - content_moderation
  - cshs
  - ctools
  - datetime
  - editor
  - entity_reference_revisions
  - features
  - field
  - field_group
  - field_permissions
  - field_validation
  - file
  - filter
  - hal
  - help
  - image
  - link
  - linkit
  - markup
  - menu_link_content
  - menu_ui
  - migrate_plus
  - node
  - options
  - page_manager
  - panels
  - paragraphs
  - path
  - pfdp
  - php
  - rdf
  - responsive_image
  - rest
  - search
  - shortcut
  - system
  - taxonomy
  - telephone
  - text
  - token_filter
  - tour
  - user
  - views
  - views_ui
  - webform
  - workflows
description: 'All of it, I shit you not. If you can navigate dependency hell better, by all means :)'
version: 8.x-0.1
package: AfrikaBurn
