name: afrikaburn_configuration
type: module
core: 8.x
dependencies:
  - block
  - block_content
  - ckeditor
  - comment
  - conditional_fields
  - contact
  - content_moderation
  - cshs
  - ctools
  - custom_add_another
  - datetime
  - editor
  - entity_reference_revisions
  - field
  - field_group
  - field_permissions
  - field_validation
  - file
  - filter
  - image
  - link
  - linkit
  - markup
  - menu_link_content
  - menu_ui
  - node
  - options
  - page_manager
  - panelizer
  - panels
  - paragraphs
  - path
  - pathauto
  - pfdp
  - php
  - rdf
  - responsive_image
  - rules
  - shortcut
  - system
  - taxonomy
  - telephone
  - text
  - token_filter
  - tour
  - user
  - views
  - views_field_view
  - webform
  - workflows
version: 8.x-1.1
package: AfrikaBurn
