bundle: afrikaburn
excluded:
  - group.settings
  - block.block.afrikaburn_group_operations
  - block.block.group_operations
  - core.entity_form_display.group_content.collectives-group_membership.default
  - core.entity_view_display.group_content.collectives-group_membership.default
  - field.field.group.collectives.field_collective_space
  - field.field.group.collectives.field_comment
  - field.field.group.collectives.field_ddt_eligible
  - field.field.group.collectives.field_manage_by_deparment
  - field.field.group_content.collectives-group_membership.group_roles
  - field.storage.group.field_collective_space
  - field.storage.group.field_comment
  - field.storage.group.field_ddt_eligible
  - field.storage.group.field_manage_by_deparment
  - field.storage.group_content.group_roles
  - group.content_type.collectives-group_membership
  - group.content_type.collectives-group_node-art
  - group.content_type.collectives-group_node-forum
  - group.content_type.collectives-group_node-update
  - group.content_type.group_content_type_5bd3888d6d5d4
  - group.content_type.group_content_type_a92d115a29281
  - group.content_type.group_content_type_df7112de289f9
  - group.role.collectives-anonymous
  - group.role.collectives-outsider
  - group.role.collectives-member
  - group.role.collectives-7d5656e25
  - group.role.collectives-1318e8721
  - group.role.collectives-c5ec0e415
  - group.role.collectives-37ab32e54
  - group.role.collectives-c3aee87b5
  - group.role.collectives-2894e0400
  - group.role.collectives-e84703432
  - group.role.collectives-3f31ffb42
  - group.role.collectives-39a85c011
  - group.role.collectives-78dcab262
  - group.role.collectives-eaeccf248
  - group.role.collectives-eabc2117c
  - group.role.collectives-5d7f2251c
  - group.role.collectives-3d17bc140
  - group.role.collectives-a416e6833
  - group.role.collectives-admin
  - group.type.collectives
  - views.view.group_members
  - views.view.group_nodes
  - core.entity_view_mode.group.token
  - core.entity_view_mode.group_content.token
required: true
