bundle: afrikaburn
excluded:
  - core.entity_view_mode.node.print
  - captcha.settings
  - google_analytics.settings
  - recaptcha.settings
  - block.block.afrikaburn_account_menu
  - block.block.afrikaburn_footer
  - block.block.afrikaburn_main_menu
  - captcha.captcha_point.user_login_form
  - captcha.captcha_point.user_pass
  - captcha.captcha_point.user_register_form
required: true
